# -*- coding: utf-8 -*-
"""Scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YusyMs0ct8FzZ-Q5ToG7V7ODC4sXCBTh
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
import math
import numpy as np

"""# Scraping"""

# ----------------------------
# Configuración URL
# ----------------------------

URL = "https://sbbl.es/stats"

params = {
    "sort": "percentage_victories",
    "order": "desc",
    "blade": "",
    "ratchet": "",
    "bit": "",
    "min_partidas": 0,
    "fecha_inicio": "",
    "fecha_fin": ""
}

response = requests.get(URL, params=params)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")
table = soup.find("table")
rows = table.find_all("tr")

#Pre-procesado

# ----------------------------
# Separación Blade/Ratchet/Bit
# ----------------------------

def separar_componentes(texto, ratchets_especiales):
    partes = texto.split()

    ratchet_idx = None

    for i, p in enumerate(partes):
        if re.match(r"\d+-\d+", p) or p in ratchets_especiales:
            ratchet_idx = i
            break

    if ratchet_idx is None:
        return texto, None, None

    # Blade = todo antes
    blade = " ".join(partes[:ratchet_idx])

    # Ratchet
    ratchet = partes[ratchet_idx]

    # Buscar la X (si existe)
    if "X" in partes:
        x_idx = partes.index("X")
        bit = " ".join(partes[x_idx + 1:]) if len(partes) > x_idx + 1 else None
    else:
        bit = " ".join(partes[ratchet_idx + 1:]) if len(partes) > ratchet_idx + 1 else None

    return blade, ratchet, bit

# ----------------------------
# Validación básica
# ----------------------------

def es_combo_valido(blade, ratchet, bit):

    if not blade or not ratchet:
        return False

    texto = f"{blade} {ratchet} {bit}".lower()

    if "selecciona" in texto:
        return False

    if ratchet.strip() == "_" or (bit and bit.strip() == "_"):
        return False

    return True

# ----------------------------
# Wilson Score
# ----------------------------

def wilson_score(wins, total, z=1.96):
    if total == 0:
        return None
    p = wins / total
    denominator = 1 + z**2 / total
    centre = p + z**2 / (2 * total)
    margin = z * math.sqrt((p * (1 - p) + z**2 / (4 * total)) / total)
    return (centre - margin) / denominator

# ----------------------------
# DEBUG FORMATO WEB
# ----------------------------

import requests
from bs4 import BeautifulSoup

URL = "https://sbbl.es/stats"

params = {
    "sort": "percentage_victories",
    "order": "desc",
    "blade": "",
    "ratchet": "",
    "bit": "",
    "min_partidas": 0,
    "fecha_inicio": "",
    "fecha_fin": ""
}

response = requests.get(URL, params=params)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")
table = soup.find("table")
rows = table.find_all("tr")

print(f"Total filas: {len(rows)}\n")

# Mostrar primeras filas útiles
max_rows = 20
count = 0

for i, row in enumerate(rows):
    cols = row.find_all("td")

    if not cols:
        continue

    combo_text = cols[0].get_text(" ", strip=True)

    print(f"Fila {i}")
    print("RAW:", combo_text)
    print("SPLIT:", combo_text.split())
    print("-" * 50)

    count += 1
    if count >= max_rows:
        break

# ----------------------------
# Scraping
# ----------------------------

ratchets_especiales = ["Turbo", "Operate", "Zillion"]

def separar_componentes(texto, ratchets_especiales):
    partes = texto.split()

    ratchet_idx = None

    # Detectar ratchet (normal o especial)
    for i, p in enumerate(partes):
        if re.match(r"\d+-\d+", p) or p in ratchets_especiales:
            ratchet_idx = i
            break

    if ratchet_idx is None:
        return texto, None, None

    # Blade = todo antes
    blade = " ".join(partes[:ratchet_idx])

    # Ratchet
    ratchet = partes[ratchet_idx]

    # Bit (después de la X si existe)
    if "X" in partes:
        x_idx = partes.index("X")
        bit = " ".join(partes[x_idx + 1:]) if len(partes) > x_idx + 1 else None
    else:
        bit = " ".join(partes[ratchet_idx + 1:]) if len(partes) > ratchet_idx + 1 else None

    return blade, ratchet, bit


data = []
i = 1

while i < len(rows):

    cols = rows[i].find_all("td")
    if not cols:
        i += 1
        continue

    combo_text = cols[0].get_text(" ", strip=True)
    winrate_text = cols[1].get_text(strip=True)
    partidas_text = cols[2].get_text(strip=True)
    eficiencia_text = cols[3].get_text(strip=True)

    # --- Formato antiguo con • ---
    if "•" in combo_text:
        parte_principal, bit = combo_text.split("•", 1)
        bit = bit.strip()
    else:
        parte_principal = combo_text
        bit = None

    # --- Separación correcta ---
    blade, ratchet, bit_text = separar_componentes(parte_principal, ratchets_especiales)

    if ratchet is None:
        i += 2
        continue

    if bit is None:
        bit = bit_text

    # --- Regla ratchets especiales ---
    if ratchet in ratchets_especiales:
        if bit is None or bit == "":
            bit = ratchet
        else:
            i += 2
            continue

    # --- Validación básica ---
    if not es_combo_valido(blade, ratchet, bit):
        i += 2
        continue

    # --- Métricas ---
    win_percent = None
    wins = None
    losses = None

    win_match = re.search(r"([\d\.]+)%", winrate_text)
    wl_match = re.search(r"(\d+)W\s*-\s*(\d+)L", winrate_text)

    if win_match:
        win_percent = float(win_match.group(1))
    if wl_match:
        wins = int(wl_match.group(1))
        losses = int(wl_match.group(2))

    try:
        partidas = int(partidas_text)
    except:
        i += 2
        continue

    try:
        eficiencia = int(re.search(r"\d+", eficiencia_text).group())
    except:
        i += 2
        continue

    # --- Detalle (fila siguiente) ---
    detalle_text = ""
    if i + 1 < len(rows):
        detalle_text = rows[i + 1].get_text(" ", strip=True)

    nums = re.findall(r"\d+\.\d+", detalle_text)

    pts_ganados = float(nums[0]) if len(nums) > 0 else None
    pts_cedidos = float(nums[1]) if len(nums) > 1 else None

    data.append({
        "Blade": blade,
        "Ratchet": ratchet,
        "Bit": bit,
        "Win %": win_percent,
        "Wins": wins,
        "Losses": losses,
        "Partidas": partidas,
        "Eficiencia": eficiencia,
        "Pts Ganados/Combate": pts_ganados,
        "Pts Cedidos/Combate": pts_cedidos
    })

    i += 2


df = pd.DataFrame(data)

# --- Wilson Score (simple) ---
if not df.empty:
    df["Wilson Score"] = df.apply(
        lambda row: wilson_score(row["Wins"], row["Partidas"])
        if pd.notna(row["Wins"]) and row["Partidas"] > 0
        else None,
        axis=1
    )

print("Dataset limpio generado correctamente")
print("Total combos válidos:", len(df))
print(df.head())

print(df.dtypes)

"""#Limpieza

## Nulos
"""

print("Valores nulos por columna:")
print(df.isnull().sum())

print(df[df.isnull().any(axis=1)])

df.dropna(inplace=True)

"""## Errores de imputación"""

#Filas con 0 partidas
df = df[df['Partidas'] > 0]

#Victorias sin puntos ganados y derrotas sin puntos cedidos
df = df[~((df['Wins'] > 0) & (df['Pts Ganados/Combate'] == 0))]
df = df[~((df['Losses'] > 0) & (df['Pts Cedidos/Combate'] == 0))]

#Ratios de victoria superiores al 100%
df = df[df['Win %'] <= 100]

#Puntos ganados y cedidos por combeta fuera del rango posible
df = df[(df['Pts Ganados/Combate'] <= 3) & (df['Pts Ganados/Combate'] >= 0)]
df = df[(df['Pts Cedidos/Combate'] <= 3) & (df['Pts Cedidos/Combate'] >= 0)]

#Verificar si hay algñun ratchet especial
ratchet_counts = df['Ratchet'].value_counts()
print("Conteo de valores repetidos en la columna 'Ratchet':")
print(ratchet_counts)

#Generar archivo csv final
df.to_csv("beyblade_stats.csv", index=False)

"""# Datasets por partes"""

df_blade = (
    df[["Blade", "Wins", "Losses", "Partidas"]]  # 👈 seleccionas columnas
    .groupby("Blade")
    .sum()
    .reset_index()
)

df_blade["Wilson Score"] = df_blade.apply(
    lambda row: wilson_score(row["Wins"], row["Partidas"])
    if row["Partidas"] > 0 else None,
    axis=1
)

df_ratchet = (
    df[["Ratchet", "Wins", "Losses", "Partidas"]]
    .groupby("Ratchet")
    .sum()
    .reset_index()
)

df_ratchet["Wilson Score"] = df_ratchet.apply(
    lambda row: wilson_score(row["Wins"], row["Partidas"])
    if row["Partidas"] > 0 else None,
    axis=1
)

df_bit = (
    df[["Bit", "Wins", "Losses", "Partidas"]]
    .groupby("Bit")
    .sum()
    .reset_index()
)

df_bit["Wilson Score"] = df_bit.apply(
    lambda row: wilson_score(row["Wins"], row["Partidas"])
    if row["Partidas"] > 0 else None,
    axis=1
)

df_blade.to_csv("blade_stats.csv", index=False)
df_ratchet.to_csv("ratchet_stats.csv", index=False)
df_bit.to_csv("bit_stats.csv", index=False)